# Site settings
title: Startsiden
tag_text: Startsiden
description: På Universitas Startsiden så finner man informasjon, dokumenter og lenker til diverse Universitas ressurser.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
